[versions]
agp = "8.7.3"
kotlin = "2.0.21"
coreKtx = "1.15.0"
pinyin4j = "2.5.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
pinyin4j = { group = "com.belerweb", name = "pinyin4j", version.ref = "pinyin4j" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
