[versions]
agp = "8.7.3"
kotlin = "2.0.21"
coreKtx = "1.15.0"
pinyin4j = "2.5.1"
nanohttpd = "2.3.1"
zxingCore = "3.5.3"
zxingEmbedded = "4.3.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
pinyin4j = { group = "com.belerweb", name = "pinyin4j", version.ref = "pinyin4j" }
nanohttpd = { group = "org.nanohttpd", name = "nanohttpd", version.ref = "nanohttpd" }
zxing-core = { group = "com.google.zxing", name = "core", version.ref = "zxingCore" }
zxing-embedded = { group = "com.journeyapps", name = "zxing-android-embedded", version.ref = "zxingEmbedded" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
